// API configuration — use relative paths so Next.js proxy handles routing
export const API_ENDPOINTS = {
  auth: {
    login: '/api/token/pair',
    register: '/api/auth/register',
    me: '/api/auth/me',
    verifyEmail: '/api/auth/verify-email',
    resendVerification: '/api/auth/resend-verification',
    passwordResetRequest: '/api/auth/password-reset-request',
    passwordResetConfirm: '/api/auth/password-reset-confirm',
    refreshToken: '/api/token/refresh',
    settings: '/api/auth/settings',
    avatar: '/api/auth/avatar',
    avatarUrl: '/api/auth/avatar-url',
    changePassword: '/api/auth/change-password',
    profile: (username) => `/api/auth/profile/${username}`,
  },
  blog: {
    posts: '/api/blog/posts',
    categories: '/api/blog/categories',
    myPosts: '/api/blog/my-posts',
    myPost: (id) => `/api/blog/my-posts/${id}`,
    uploadImage: '/api/blog/upload-image',
    imageUrl: '/api/blog/image-url',
    comments: (postId) => `/api/blog/posts/${postId}/comments/`,
    comment: (commentId) => `/api/blog/comments/${commentId}/`,
    likePost: (slug) => `/api/blog/posts/${slug}/like/`,
    tags: '/api/blog/tags',
    tag: (id) => `/api/blog/tags/${id}`,
  },
  admin: {
    dashboard: '/api/admin/dashboard/',
    users: '/api/admin/users/',
    user: (id) => `/api/admin/users/${id}/`,
    userRole: (id) => `/api/admin/users/${id}/role/`,
    userSuspend: (id) => `/api/admin/users/${id}/suspend/`,
    posts: '/api/admin/posts/',
    postStatus: (id) => `/api/admin/posts/${id}/status/`,
    deletePost: (id) => `/api/admin/posts/${id}/`,
    recipes: '/api/admin/recipes/',
    recipeStatus: (id) => `/api/admin/recipes/${id}/status/`,
    deleteRecipe: (id) => `/api/admin/recipes/${id}/`,
    categories: '/api/admin/categories/',
    category: (id) => `/api/admin/categories/${id}/`,
    categoryImage: (id) => `/api/admin/categories/${id}/image/`,
    tags: '/api/admin/tags/',
    tag: (id) => `/api/admin/tags/${id}/`,
  },
  recipes: {
    list:          '/api/recipes/',
    detail:        (slug) => `/api/recipes/${slug}/`,
    create:        '/api/recipes/',
    update:        (slug) => `/api/recipes/${slug}/`,
    delete:        (slug) => `/api/recipes/${slug}/`,
    myRecipes:     '/api/recipes/my-recipes/',
    myRecipe:      (id) => `/api/recipes/my-recipes/${id}/`,
    rate:          (id) => `/api/recipes/${id}/rate/`,
    rating:        (id) => `/api/recipes/${id}/rating/`,
    comments:      (id) => `/api/recipes/${id}/comments/`,
    comment:       (id) => `/api/recipes/comments/${id}/`,
    dietaryLabels: '/api/recipes/dietary-labels/',
  },
};
